{% set name = "tango-controls-tui" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SKAJohanVenter/tango-controls-tui/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6c5439904fb361ab08a3ecb02cd11be24d29f45cba1cb3cc5d153b7e34dbc0c2

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
  host:
    - cpptango
    - cppzmq
    - omniorb

test:
  commands:
    - tango-controls-tui --help

about:
  home: https://github.com/SKAJohanVenter/tango-controls-tui
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.GPL-3.0
    - THIRDPARTY.yml
  summary: TUI to explore tango devices
  description: |
    Text-based user interfaces to explore tango devices.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://github.com/SKAJohanVenter/tango-controls-tui

extra:
  recipe-maintainers:
    - beenje
    - SKAJohanVenter
